### ISSUE TITLE
Click the post update button I get a notice and a warning

### ISSUE THREAD

**Issue by jwight1234** [ahoereth/featured-video-plus#1]
When I click the post update button I get a notice and a warning.

Notice: Undefined variable: set_featimg in /Applications/MAMP/htdocs/clients-sites/ees/wp-content/plugins/featured-video-plus/php/backend.php on line 599

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/clients-sites/ees/wp-content/plugins/featured-video-plus/php/backend.php:599) in /Applications/MAMP/htdocs/clients-sites/ees/wp-includes/pluggable.php on line 876

Iam using a Vimeo test video (http://vimeo.com/45417241) and using the custom featured image as the video thumbnail. If you need any other info just let me know and i will send it your way. 
![screenshot](https://f.cloud.github.com/assets/3188128/402978/d1f1bed2-a90e-11e2-880d-9a0d15feb5c4.png)

**Comment by ahoereth** [comment]
Fixed in 2.0.0+
