### ISSUE TITLE
Videos don't embed on secure sites

### ISSUE THREAD

**Issue by mikemanger** [ahoereth/featured-video-plus#3]
We have SSL on our site, any vimeo videos don't work. A work around is to just always load the https URL however I think it might be better to use the `WP_oEmbed->get_html()` function to get the iframe html.

**Comment by native-apps** [comment]
Oh hmm.  Yeah, just noticed that my SSL sites won't work with Featured Video Plus. Was there a fix posted yet?

**Comment by mgtldev** [comment]
just adding my voice to this issue. also getting the same problem on my https only site. hard-editing the urls in general.php to use https fixes it as a workaround but would be great if it could check for the WP https setting  and render links accordingly.

**Comment by ahoereth** [comment]
Version 2.0.0 is a major overhaul of the whole code base and includes a shift to oEmbed for retrieving embed codes. See [class-oembed.php](https://github.com/ahoereth/featured-video-plus/blob/2.0.0/php/class-oembed.php) which is an extension of WordPress'  [native oEmbed class](https://github.com/WordPress/WordPress/blob/4.0/wp-includes/class-oembed.php).

**Comment by ahoereth** [comment]
Fixed in 2.0.0 by the use of oEmbed.
